sudo: required
services:
  - docker

before_install:
  - docker build -t minhnhat09/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run minhnhat09/react-test npm test -- --coverage

after_success:
  - docker build -t minhnhat09/multi-client ./client
  - docker build -t minhnhat09/multi-nginx ./nginx
  - docker build -t minhnhat09/multi-server ./server
  - docker build -t minhnhat09/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push minhnhat09/multi-client
  - docker push minhnhat09/multi-nginx
  - docker push minhnhat09/multi-server
  - docker push minhnhat09/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-3-923105483313
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
